name: Debug and Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build & Inspect
        run: |
          flutter config --enable-web
          flutter build web --release
          # نسخ ملف الإعدادات للمجلد
          cp vercel.json build/web/
          
          echo "--- فحص محتويات المجلد النهائي ---"
          ls -R build/web  # هاد السطر رح يحكيلنا لو index.html موجود فعلاً

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          cd build/web
          # الرفع باستخدام الـ CLI المباشر
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}